### ISSUE TITLE
[Request] Tutorial to make custom mica backgrounds?

### ISSUE THREAD

**Issue by KibSquib48** [MazeoGH/discord-mica#1]
I love this theme but none of the mica backgrounds quite match my wallpaper so I'd like to make my own. Could there be a tutorial on how to make our own backgrounds for the theme?

**Comment by Void48** [comment]
> I love this theme but none of the mica backgrounds quite match my wallpaper so I'd like to make my own. Could there be a tutorial on how to make our own backgrounds for the theme?

I agree with this

**Comment by MazeoGH** [comment]
I wrote a small text tutorial, and pushed a new release to include a custom base.
