### ISSUE TITLE
Theme won't import

### ISSUE THREAD

**Issue by CeruleanDerpo** [MazeoGH/discord-mica#5]
Every time I import any theme from the folder (custom ones included) I get the following error:
```
Could not be compiled. See console for details.
    at Object.loadAddon (<anonymous>:4:268126)
    at Object.loadAddon (<anonymous>:4:310889)
    at FSWatcher.<anonymous> (<anonymous>:4:266254)
```

**Comment by DerpyPlayz18** [comment]
nevermind resolved: if anyone has the same issue you have to download the files from the releases bar on the right of your screen.
